In [3]:
import numpy as np
import pandas as pd
from scipy import stats
import seaborn as sns
import matplotlib.pyplot as plt

#### **Task 7**: Test the hypothesis whether planes fly faster when there is the departure delay?

In [20]:
path = '/home/jewelle/data_bootcamp/'
flights_df =  pd.read_csv(path +'flights_df_clean.csv')
flights_df.head()

,fl_date,branded_code_share,mkt_carrier,mkt_carrier_fl_num,op_unique_carrier,tail_num,op_carrier_fl_num,origin_airport_id,origin,origin_city_name,...,crs_elapsed_time,actual_elapsed_time,air_time,flights,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,2018-01-23 00:00:00,UA_CODESHARE,UA,3405,YX,N653RW,3405,10821,BWI,"Baltimore, MD",...,75.0,89.0,49.0,1.0,169.0,0.0,0.0,0.0,0.0,0.0
1,2018-11-15 00:00:00,AA_CODESHARE,AA,5683,OH,N594NN,5683,11057,CLT,"Charlotte, NC",...,136.0,122.0,99.0,1.0,640.0,0.0,0.0,0.0,0.0,0.0
2,2019-10-29 00:00:00,WN,WN,2434,WN,N432WN,2434,12889,LAS,"Las Vegas, NV",...,155.0,156.0,139.0,1.0,867.0,0.0,0.0,0.0,0.0,0.0
3,2019-11-14 00:00:00,B6,B6,577,B6,N968JT,577,11697,FLL,"Fort Lauderdale, FL",...,385.0,371.0,346.0,1.0,2584.0,0.0,0.0,0.0,0.0,0.0
4,2019-05-22 00:00:00,DL_CODESHARE,DL,3762,OO,N8933B,3762,10397,ATL,"Atlanta, GA",...,107.0,90.0,73.0,1.0,508.0,0.0,0.0,0.0,0.0,0.0

In [23]:
# speed is distance/time, check values for air_time, distance are filled in
flights_df['air_time'].isna().sum(), flights_df['distance'].isna().sum()
#Division with values of 0 could be problematic so...

(0, 0)

In [33]:
#Just to check
flights_df[(flights_df['air_time']==0.0) | (flights_df['distance'] == 0.0)]

,fl_date,branded_code_share,mkt_carrier,mkt_carrier_fl_num,op_unique_carrier,tail_num,op_carrier_fl_num,origin_airport_id,origin,origin_city_name,...,actual_elapsed_time,air_time,flights,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay,avg_speed
59,2018-10-02 00:00:00,B6,B6,815,B6,N375JB,815,10721,BOS,"Boston, MA",...,0.0,0.0,1.0,395.0,0.0,0.0,0.0,0.0,0.0,inf
101,2019-10-14 00:00:00,DL_CODESHARE,DL,5010,9E,N8839E,5010,10397,ATL,"Atlanta, GA",...,0.0,0.0,1.0,500.0,0.0,0.0,0.0,0.0,0.0,inf
150,2018-03-21 00:00:00,B6,B6,2679,B6,N353JB,2679,10721,BOS,"Boston, MA",...,0.0,0.0,1.0,200.0,0.0,0.0,0.0,0.0,0.0,inf
151,2018-05-25 00:00:00,DL_CODESHARE,DL,4647,OO,N921EV,4647,14696,SBN,"South Bend, IN",...,0.0,0.0,1.0,566.0,0.0,0.0,0.0,0.0,0.0,inf
194,2019-08-13 00:00:00,WN,WN,1697,WN,N280WN,1697,11278,DCA,"Washington, DC",...,0.0,0.0,1.0,1158.0,0.0,0.0,0.0,0.0,0.0,inf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9815,2018-11-25 00:00:00,UA_CODESHARE,UA,4792,AX,0,4792,13930,ORD,"Chicago, IL",...,0.0,0.0,1.0,286.0,0.0,0.0,0.0,0.0,0.0,inf
9836,2018-02-11 00:00:00,AA_CODESHARE,AA,3919,MQ,N928AE,3919,13930,ORD,"Chicago, IL",...,0.0,0.0,1.0,160.0,0.0,0.0,0.0,0.0,0.0,inf
9909,2019-02-27 00:00:00,WN,WN,1687,WN,N781WN,1687,12191,HOU,"Houston, TX",...,0.0,0.0,1.0,920.0,0.0,0.0,0.0,0.0,0.0,inf
9910,2019-03-26 00:00:00,WN,WN,2300,WN,0,2300,14683,SAT,"San Antonio, TX",...,0.0,0.0,1.0,1069.0,0.0,0.0,0.0,0.0,0.0,inf
9997,2018-10-11 00:00:00,AA_CODESHARE,AA,5657,OH,0,5657,11057,CLT,"Charlotte, NC",...,0.0,0.0,1.0,140.0,0.0,0.0,0.0,0.0,0.0,inf

In [37]:
flights_df[(flights_df['air_time']==0.0)]

,fl_date,branded_code_share,mkt_carrier,mkt_carrier_fl_num,op_unique_carrier,tail_num,op_carrier_fl_num,origin_airport_id,origin,origin_city_name,...,actual_elapsed_time,air_time,flights,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay,avg_speed
59,2018-10-02 00:00:00,B6,B6,815,B6,N375JB,815,10721,BOS,"Boston, MA",...,0.0,0.0,1.0,395.0,0.0,0.0,0.0,0.0,0.0,inf
101,2019-10-14 00:00:00,DL_CODESHARE,DL,5010,9E,N8839E,5010,10397,ATL,"Atlanta, GA",...,0.0,0.0,1.0,500.0,0.0,0.0,0.0,0.0,0.0,inf
150,2018-03-21 00:00:00,B6,B6,2679,B6,N353JB,2679,10721,BOS,"Boston, MA",...,0.0,0.0,1.0,200.0,0.0,0.0,0.0,0.0,0.0,inf
151,2018-05-25 00:00:00,DL_CODESHARE,DL,4647,OO,N921EV,4647,14696,SBN,"South Bend, IN",...,0.0,0.0,1.0,566.0,0.0,0.0,0.0,0.0,0.0,inf
194,2019-08-13 00:00:00,WN,WN,1697,WN,N280WN,1697,11278,DCA,"Washington, DC",...,0.0,0.0,1.0,1158.0,0.0,0.0,0.0,0.0,0.0,inf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9815,2018-11-25 00:00:00,UA_CODESHARE,UA,4792,AX,0,4792,13930,ORD,"Chicago, IL",...,0.0,0.0,1.0,286.0,0.0,0.0,0.0,0.0,0.0,inf
9836,2018-02-11 00:00:00,AA_CODESHARE,AA,3919,MQ,N928AE,3919,13930,ORD,"Chicago, IL",...,0.0,0.0,1.0,160.0,0.0,0.0,0.0,0.0,0.0,inf
9909,2019-02-27 00:00:00,WN,WN,1687,WN,N781WN,1687,12191,HOU,"Houston, TX",...,0.0,0.0,1.0,920.0,0.0,0.0,0.0,0.0,0.0,inf
9910,2019-03-26 00:00:00,WN,WN,2300,WN,0,2300,14683,SAT,"San Antonio, TX",...,0.0,0.0,1.0,1069.0,0.0,0.0,0.0,0.0,0.0,inf
9997,2018-10-11 00:00:00,AA_CODESHARE,AA,5657,OH,0,5657,11057,CLT,"Charlotte, NC",...,0.0,0.0,1.0,140.0,0.0,0.0,0.0,0.0,0.0,inf

In [38]:
flights_df[(flights_df['distance'] == 0.0)]

Empty DataFrame
Columns: [fl_date, branded_code_share, mkt_carrier, mkt_carrier_fl_num, op_unique_carrier, tail_num, op_carrier_fl_num, origin_airport_id, origin, origin_city_name, dest_airport_id, dest, dest_city_name, crs_dep_time, dep_time, dep_delay, taxi_out, wheels_off, wheels_on, taxi_in, crs_arr_time, arr_time, arr_delay, cancelled, diverted, crs_elapsed_time, actual_elapsed_time, air_time, flights, distance, carrier_delay, weather_delay, nas_delay, security_delay, late_aircraft_delay, avg_speed]
Index: []

[0 rows x 36 columns]

In [48]:
flights_df = flights_df.drop(flights_df[(flights_df['air_time']==0.0)].index)

In [49]:
#check there are no airtime values of 0 again
flights_df[(flights_df['air_time']==0.0)]

Empty DataFrame
Columns: [fl_date, branded_code_share, mkt_carrier, mkt_carrier_fl_num, op_unique_carrier, tail_num, op_carrier_fl_num, origin_airport_id, origin, origin_city_name, dest_airport_id, dest, dest_city_name, crs_dep_time, dep_time, dep_delay, taxi_out, wheels_off, wheels_on, taxi_in, crs_arr_time, arr_time, arr_delay, cancelled, diverted, crs_elapsed_time, actual_elapsed_time, air_time, flights, distance, carrier_delay, weather_delay, nas_delay, security_delay, late_aircraft_delay, avg_speed]
Index: []

[0 rows x 36 columns]

In [51]:
#speed = distance/airtime
#data is in miles per minute
#miles:km is 1:1.609

flights_df['avg_speed'] = (flights_df['distance']/flights_df['air_time'])*1.61*60 #convert minutes to hours

In [52]:
flights_df['avg_speed']

0       333.171429
1       624.484848
2       602.533813
3       721.428902
4       672.230137
           ...
9994    404.512500
9995    751.595122
9996    474.600000
9998    530.812121
9999    798.267273
Name: avg_speed, Length: 9796, dtype: float64

In [60]:
#where dep_delay > 0
delay_flightspeed = flights_df.loc[(flights_df['dep_delay'] > 0), 'avg_speed']

In [61]:
#where dep_delay = 0
delay_zero_speed = flights_df.loc[(flights_df['dep_delay'] == 0), 'avg_speed']

In [65]:
#We take the HNull that there is no difference in average(mean) flight speed with regards to dep_delay
def filter_outliers(data, m = 3):
    return data[abs(data - np.mean(data)) < m * np.std(data)]

In [69]:
delay_flightspeed_filtered = filter_outliers(delay_flightspeed, m = 3)
delay_zero_speed_filtered = filter_outliers(delay_zero_speed, m = 2)

In [70]:
delay_flightspeed_filtered.mean(), delay_zero_speed_filtered.mean()

(655.5479724876949, 665.7039545601572)

In [75]:
#Z-test
from statsmodels.stats.weightstats import ztest
ztest, pval = ztest(delay_flightspeed_filtered, delay_zero_speed_filtered)

In [78]:
print("p-value",pval)
if pval < 0.05:
      print("we reject null hypothesis")
else:
      print("we accept null hypothesis")

p-value 0.07409958732493235
we accept null hypothesis

In [79]:
#Two-sample t-test
from scipy.stats import ttest_ind
ttest, pval = ttest_ind(delay_flightspeed_filtered[:1000], delay_zero_speed_filtered[:1000])

In [80]:
print("p-value",pval)
if pval < 0.05:
      print("we reject null hypothesis")
else:
      print("we accept null hypothesis")

p-value 0.13918934958957088
we accept null hypothesis

Reasons why they might not be faster:
* Delays due to inclement weather do not disappear after take-off. 
* Delays due to large payload (large volume of passengers + cargo) aren't going to help flight speed
* Fuel Limitations